services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MODEL_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    working_dir: /app

models:
  llm:
    image: ai/qwen2.5:3b
    
networks:
  default:
    name: project-recommender
